/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

(function (Drupal, drupalSettings) {
  var SitewideAlert = function (_React$Component) {
    _inherits(SitewideAlert, _React$Component);

    function SitewideAlert(props) {
      _classCallCheck(this, SitewideAlert);

      var _this = _possibleConstructorReturn(this, (SitewideAlert.__proto__ || Object.getPrototypeOf(SitewideAlert)).call(this, props));

      _this.state = {
        dismissed: _this.alertWasDismissed(props.dismissalIgnoreBefore),
        showOnThisPage: _this.shouldShowOnThisPage(props.showOnPages, props.negateShowOnPages)
      };
      _this.dismissAlert = _this.dismissAlert.bind(_this);
      _this.alertWasDismissed = _this.alertWasDismissed.bind(_this);
      _this.shouldShowOnThisPage = _this.shouldShowOnThisPage.bind(_this);
      return _this;
    }

    _createClass(SitewideAlert, [{
      key: 'componentDidUpdate',
      value: function componentDidUpdate(prevProps) {
        if (this.props.dismissalIgnoreBefore !== prevProps.dismissalIgnoreBefore || this.props.showOnPages !== prevProps.showOnPages || this.props.negateShowOnPages !== prevProps.negateShowOnPages) {
          this.setState({
            dismissed: this.alertWasDismissed(this.props.dismissalIgnoreBefore),
            showOnThisPage: this.shouldShowOnThisPage(this.props.showOnPages, this.props.negateShowOnPages)
          });
        }
      }
    }, {
      key: 'shouldShowOnThisPage',
      value: function shouldShowOnThisPage() {
        var pages = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : [];
        var negate = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : true;

        if (pages.length === 0) {
          return true;
        }

        var pagePathMatches = false;
        var currentPath = window.location.pathname;

        for (var i = 0; i < pages.length; i++) {
          var baseUrl = drupalSettings.path.baseUrl.slice(0, -1);
          var page = baseUrl + pages[i];

          if (page.charAt(page.length - 1) === '*') {
            if (currentPath.startsWith(page.substring(0, page.length - 1))) {
              pagePathMatches = true;
              break;
            }
          } else if (page === currentPath) {
            pagePathMatches = true;
            break;
          }
        }

        return negate ? !pagePathMatches : pagePathMatches;
      }
    }, {
      key: 'alertWasDismissed',
      value: function alertWasDismissed(ignoreDismissalBefore) {
        if (!('alert-dismissed-' + this.props.uuid in window.localStorage)) {
          return false;
        }

        var dismissedAtTimestamp = Number(window.localStorage.getItem('alert-dismissed-' + this.props.uuid));

        if (dismissedAtTimestamp < ignoreDismissalBefore) {
          return false;
        }

        return true;
      }
    }, {
      key: 'dismissAlert',
      value: function dismissAlert() {
        window.localStorage.setItem('alert-dismissed-' + this.props.uuid, String(Math.round(new Date().getTime() / 1000)));
        this.setState({
          dismissed: true,
          showOnThisPage: this.state.showOnThisPage
        });
      }
    }, {
      key: 'render',
      value: function render() {
        if (this.props.dismissible && this.state.dismissed) {
          return null;
        }

        if (!this.state.showOnThisPage) {
          return null;
        }

        var alertClasses = 'sitewide-alert alert';
        if (this.props.styleClass !== '') {
          alertClasses += ' ' + this.props.styleClass;
        }

        return React.createElement(
          'div',
          { className: alertClasses, role: 'alert' },
          React.createElement('span', { dangerouslySetInnerHTML: { __html: this.props.message } }),
          this.props.dismissible && React.createElement(
            'button',
            { className: 'close', onClick: this.dismissAlert, 'aria-label': 'Close' },
            React.createElement(
              'span',
              { 'aria-hidden': 'true' },
              '\xD7'
            )
          )
        );
      }
    }]);

    return SitewideAlert;
  }(React.Component);

  var SitewideAlerts = function (_React$Component2) {
    _inherits(SitewideAlerts, _React$Component2);

    function SitewideAlerts(props) {
      _classCallCheck(this, SitewideAlerts);

      var _this2 = _possibleConstructorReturn(this, (SitewideAlerts.__proto__ || Object.getPrototypeOf(SitewideAlerts)).call(this, props));

      _this2.state = {
        error: null,
        isLoaded: false,
        sitewideAlerts: []
      };
      return _this2;
    }

    _createClass(SitewideAlerts, [{
      key: 'componentDidMount',
      value: function componentDidMount() {
        var _this3 = this;

        this.getAlerts();
        if (drupalSettings.sitewideAlert.automaticRefresh === true) {
          this.interval = setInterval(function () {
            _this3.getAlerts();
          }, drupalSettings.sitewideAlert.refreshInterval < 1000 ? 1000 : drupalSettings.sitewideAlert.refreshInterval);
        }
      }
    }, {
      key: 'componentWillUnmount',
      value: function componentWillUnmount() {
        clearInterval(this.interval);
      }
    }, {
      key: 'getAlerts',
      value: function getAlerts() {
        var _this4 = this;

        fetch(window.location.origin + drupalSettings.path.baseUrl + drupalSettings.path.pathPrefix + 'sitewide_alert/load').then(function (res) {
          return res.json();
        }).then(function (result) {
          _this4.setState({
            isLoaded: true,
            sitewideAlerts: result.sitewideAlerts
          });
        }, function (error) {
          _this4.setState({
            isLoaded: true,
            error: error
          });
        });
      }
    }, {
      key: 'render',
      value: function render() {
        var _state = this.state,
            error = _state.error,
            isLoaded = _state.isLoaded,
            sitewideAlerts = _state.sitewideAlerts;

        if (error) {
          console.log('Unable to to load alerts.');
          return React.createElement('div', null);
        } else if (!isLoaded) {
          return React.createElement('div', null);
        } else {
          return React.createElement(
            'div',
            null,
            sitewideAlerts.map(function (sitewideAlert) {
              return React.createElement(SitewideAlert, {
                key: sitewideAlert.uuid,
                uuid: sitewideAlert.uuid,
                message: sitewideAlert.message,
                styleClass: sitewideAlert.styleClass,
                dismissible: sitewideAlert.dismissible,
                dismissalIgnoreBefore: sitewideAlert.dismissalIgnoreBefore,
                showOnPages: sitewideAlert.showOnPages,
                negateShowOnPages: sitewideAlert.negateShowOnPages
              });
            })
          );
        }
      }
    }]);

    return SitewideAlerts;
  }(React.Component);

  Drupal.behaviors.sitewide_alert_init = {
    attach: function attach(context, settings) {
      ReactDOM.render(React.createElement(SitewideAlerts, null), document.getElementById('sitewide-alert'));
    }
  };
})(Drupal, drupalSettings);;
(function ($) {

  "use strict";

  $.fn.mobileMenu = function (options) {
    var settings = $.extend({
      targetWrapper: '.navbar-we-mega-menu',
      accordionMenu: 'true',
      toggledClass: 'toggled',
      pageSelector: 'body'
    }, options);

    if ($(window).width() <= 991) {
      $(settings.targetWrapper).addClass('mobile-main-menu');
    }

    var toggleButton = this;

    $(window).resize(function () {
      if ($(window).width() <= 991) {
        $(settings.targetWrapper).addClass('mobile-main-menu');
      } else {
        $(settings.targetWrapper).removeClass('mobile-main-menu');
        $('body').css('overflow', '');
        $('body').css('height', '');
        $('body').css('position', '');
        $(settings.pageSelector).removeClass(settings.toggledClass);
        $(settings.pageSelector).find('.overlay').remove();
        $(settings.pageSelector).css('position', '');
        item.removeClass('open');
        item.find('ul').css('display', '');
      }
    });

    function _weMegaMenuClear() {
      var wrapper = $(settings.pageSelector);
      var overlay = wrapper.find('.overlay');
      overlay.remove();
      wrapper.css({
        'width': '',
        'position': ''
      });
      wrapper.removeClass(settings.toggledClass);
      wrapper.find('div.region-we-mega-menu nav').removeClass('we-mobile-megamenu-active');

      if (overlay.length > 0) {
        wrapper.find('.btn-close').remove();
        overlay.remove();
        $('body').css('overflow', '');
        $('body').css('height', '');
        $('body').css('position', '');
      }
    }

    this.off('click.mobileMenu');
    this.on('click.mobileMenu', function (e) {
      var targetWrapper = $(this).closest('div.region-we-mega-menu').find('nav.navbar-we-mega-menu');
      var wrapper = $(settings.pageSelector);
      if (!wrapper.hasClass(settings.toggledClass)) {
        wrapper.addClass(settings.toggledClass).css('position', 'relative');
        $(settings.targetWrapper).addClass('mobile-main-menu');
        targetWrapper.addClass('we-mobile-megamenu-active');
        if (wrapper.find('.overlay').length == 0) {
          var overlay = $('<div class="overlay"></div>');
          overlay.prependTo(wrapper);
          overlay.click(function () {
            _weMegaMenuClear();
          });
          $('body').css('overflow', 'hidden');
          $('body').css('btn-close', 'hidden');
          $('body').css('height', '100%');
          $('body').css('position', 'relative');
        }
        if (wrapper.find('.btn-close').length == 0) {
          var btnClose = $('<span class="btn-close"></span>');
          btnClose.prependTo(wrapper);

          $('.btn-close').on('click', function (e) {
            _weMegaMenuClear();
            e.preventDefault();
            return false;
          });
        }

      } else {
        _weMegaMenuClear();
      }
      e.preventDefault();
      e.stopPropagation();
    });

    if (settings.accordionMenu == 'true') {
      var targetWrapper = $(this).closest('div.region-we-mega-menu').find('nav.navbar-we-mega-menu');
      var menu = $(targetWrapper).find('ul.we-mega-menu-ul').first();
      var item = menu.find('> li[data-submenu=1]');
      var item_active = menu.find('> li[data-submenu=1].active');
      if ($(window).width() <= 991) {
        item_active.addClass('open');
        item_active.find('> ul').css('display', 'block');
      }
      item.click(function (e) {
        if ($(window).width() <= 991) {
          var $this = $(this);
          var $sub_menu_inner = $this.find('> .we-mega-menu-submenu');
          if (!$this.hasClass('open')) {
            $(item).not($this).removeClass('open');
            item.find('> .we-mega-menu-submenu').slideUp();
            $this.toggleClass('open');
            if ($this.hasClass('open')) {
              $sub_menu_inner.slideDown();
              setTimeout(function () {
                $(targetWrapper).animate({
                  scrollTop: $this.offset().top
                }, 700);
              }, 500);

            } else {
              $sub_menu_inner.slideUp();
            }
            return false;
          }
        }
      });
    }
  }

}(jQuery));;
Drupal.WeMegaMenuFrontEnd = Drupal.WeMegaMenuFrontEnd || {};
Drupal.WeMegaMenuFrontEnd.mobileThreadHold = 1024;
Drupal.WeMegaMenuFrontEnd.megamenuActivated = false;

(function ($, Drupal, drupalSettings) {
  "use strict";

  Drupal.behaviors.kMegaMenuFrontEndAction = {
    attach: function (context) {
      $(window).on('load', function() {
        Drupal.WeMegaMenuFrontEnd.init();
        Drupal.WeMegaMenuFrontEnd.mobileMenu();
      })
    }
  };

  Drupal.WeMegaMenuFrontEnd.init = function() {
    if(Drupal.WeMegaMenuFrontEnd.megamenuActivated) {
      return;
    }
    Drupal.WeMegaMenuFrontEnd.megamenuActivated = true;
  	var megamenu = $('nav.navbar-we-mega-menu');
  	if(megamenu.hasClass('click-action')) {
  	  megamenu.find('ul li.dropdown-menu > a').click(function() {
  	  	var li = $(this).closest("li");

  	  	if(li.hasClass("clicked")) {
          li.closest('ul').find('li').removeClass('clicked');
          li.closest('.we-mega-menu-row').find('li').removeClass('clicked');
  	  	  li.removeClass("clicked");
          megamenu.removeClass("has-clicked");
  	  	} else {
          li.closest('ul').find('li').removeClass('clicked');
          li.closest('.we-mega-menu-row').find('li').removeClass('clicked');
	  	    li.closest("ul").children("li.dropdown-menu").removeClass("clicked");
  		    li.addClass("clicked");
          megamenu.addClass("has-clicked");
  	  	}
        if($(window).outerWidth() > Drupal.WeMegaMenuFrontEnd.mobileThreadHold) {
          return false;
        }
  	  });
  	  megamenu.find('ul li.dropdown-menu > a').dblclick(function() {
        if($(window).outerWidth() > Drupal.WeMegaMenuFrontEnd.mobileThreadHold) {
    	  	window.location.href = $(this).attr("href");
        }
  	  });
      megamenu.click(function(event) {
        event.stopPropagation();
      })
      $("body").click(function() {
        megamenu.find("ul li.dropdown-menu.clicked").removeClass('clicked');
        megamenu.removeClass("has-clicked");
      });
  	}
  };

  Drupal.WeMegaMenuFrontEnd.mobileMenu = function() {
    $('div.region-we-mega-menu a.navbar-toggle').mobileMenu();
    
    // $('div.region-we-mega-menu a.navbar-toggle').mobileMenu({
      // pageSelector: 'body',
      // targetWrapper: '.navbar-we-mega-menu'
    // });

    // $('#menu-toggle-wemegamenu').mobileMenu();
  };
})(jQuery, Drupal, drupalSettings);;
/**
 * @file
 * Initializes all modifications.
 */

(function ($, Drupal) {

  'use strict';

  Drupal.behaviors.modifiers = {

    attach: function attach(context, settings) {
      // Process only if there are some modifiers.
      if (typeof settings.modifiers !== 'undefined') {
        this.initAttributes(context, settings);
        this.initSettings(context, settings);
      }
    },

    initSettings: function (context, settings) {
      // Skip processing if there are no modifications.
      if (typeof settings.modifiers.settings !== 'undefined') {
        var modifications = [];

        // Group all modifications into single array.
        $.each(settings.modifiers.settings, function (index, group) {
          modifications = modifications.concat(group);
        });

        // Process all modifications.
        $.each(modifications, function (index, modification) {
          var callback = window[modification.namespace][modification.callback];
          if (typeof callback === 'function') {
            // Check number of callback arguments.
            if (callback.length > 3) {
              callback(context, modification.selector, modification.media, modification.args);
            }
            else {
              // Callback without context for backward compatibility.
              callback(modification.selector, modification.media, modification.args);
            }
          }
        });
      }
    },

    initAttributes: function (context, settings) {
      // Skip processing if there are no attributes.
      if (typeof settings.modifiers.attributes !== 'undefined') {
        var attributes = {};

        // Group all attributes into single array.
        $.each(settings.modifiers.attributes, function (index, group) {
          $.each(group, function (media, selectors) {
            // Initialize array for this media.
            if (typeof attributes[media] === 'undefined') {
              attributes[media] = {};
            }
            $.each(selectors, function (selector, values) {
              attributes[media][selector] = values;
            });
          });
        });

        // Process all attributes immediately.
        this.toggleAttributes(context, attributes);

        var that = this;
        // Process all attributes again after resize.
        window.addEventListener('resize', function () {
          that.toggleAttributes(context, attributes);
        });
      }
    },

    toggleAttributes: function (context, attributes) {
      var enable = {};
      var disable = {};

      // Check all media queries validity and split selectors to sets.
      $.each(attributes, function (media, selectors) {
        if (window.matchMedia(media).matches) {
          // Fill these selectors for enabling.
          $.each(selectors, function (selector, values) {
            enable[selector] = values;
          });
        }
        else {
          // Fill these selectors for disabling.
          $.each(selectors, function (selector, values) {
            disable[selector] = values;
          });
        }
      });

      // Remove unwanted attributes from target objects.
      $.each(disable, function (selector, values) {
        var element = $(selector, context);
        if (element.length) {
          // Process all attributes.
          $.each(values, function (attribute, value) {
            if (attribute === 'class') {
              $.each(value, function (index, item) {
                element.removeClass(item);
              });
            }
            else {
              element.prop(attribute, null);
            }
          });
        }
      });

      // Set required attributes to target objects.
      $.each(enable, function (selector, values) {
        var element = $(selector, context);
        if (element.length) {
          // Process all attributes.
          $.each(values, function (attribute, value) {
            if (attribute === 'class') {
              $.each(value, function (index, item) {
                element.addClass(item);
              });
            }
            else if (typeof value === 'object') {
              element.prop(attribute, value.join(' '));
            }
            else {
              element.prop(attribute, value);
            }
          });
        }
      });
    }
  };

})(jQuery, Drupal);
;
